version: '3.8'

services:
  mongo1:
    container_name: mongo1
    image: mongo:latest
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
      - ./scripts/init.js:/scripts/init.js
      - './data:/data/db'
    networks:
      - mongo-network
    ports:
      - 37017:27017
    depends_on:
      - mongo2
      - mongo3
    links:
      - mongo2
      - mongo3
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-mongo-set" ]

  mongo2:
    container_name: mongo2
    image: mongo:latest
    networks:
      - mongo-network
    ports:
      - 37018:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-mongo-set" ]
    
  mongo3:
    container_name: mongo3
    image: mongo:latest
    networks:
      - mongo-network
    ports:
      - 37019:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "my-mongo-set" ]

networks:
  mongo-network:
    driver: bridge